services:
  postgres:
    image: postgres:15
    restart: on-failure
    container_name: ${DOCKER_CONTAINER}
    env_file:
      - .env
      - example.env
    environment:
      - POSTGRES_DB=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${HOST_PORT}:5432"
    volumes:
      - ./:/bootcamp/
      - ./data.dump:/docker-entrypoint-initdb.d/data.dump
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-15-data:/var/lib/postgresql/data

volumes:
  postgres-15-data:
